#!/usr/bin/python
import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

from app.models import *
app.config.from_pyfile('deploy.cfg')

db.create_all()
config = Config.query.all()

settings = [["server-name","Alice"],["adminName","admin"],["password","password"]]
if not config:
    print "Wrinting new config"
    for setting in settings:
        newConfig = Config(setting[0],setting[1])
        db.session.add(newConfig)
    db.session.commit()

from app.views import *
from app import app as application
